# Generated by Django 3.0.9 on 2020-09-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
