# Generated by Django 3.0.9 on 2020-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
