# Generated by Django 3.0.9 on 2020-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userdetail_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
