# Generated by Django 3.0.9 on 2020-08-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200823_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addPost',
        ),
    ]
