# Generated by Django 3.0.9 on 2020-08-25 23:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200825_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
